server:
  name: go-subscription
  port: 8080

log:
  level: debug
  map:
    time: "@timestamp"
    msg: message

mongo:
  uri: mongodb+srv://dbUser:Demoaccount1@projectdemo.g0lah.mongodb.net
  database: masterdata

batch:
  batch_size: 3
  timeout: 39000
  limit_retry: 3
  key: key
  goroutines: false

sub:
  subscription_id: users-sub
  subscription:
    max_outstanding_messages: 10000000
    num_goroutines: 5
  client:
    credentials:

pub:
  topic_id: users
  topic:
    delay_threshold: 100
    count_threshold: 1
  client:
    credentials: