server:
  name: go-subscription
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

mongo:
  uri: mongodb+srv://dbUser:Demoaccount1@projectdemo.g0lah.mongodb.net
  database: masterdata

batch:
  batch_size: 3
  timeout: 18000
  limit_retry: 3
  key: key
  goroutines: false

reader:
  brokers: tricycle-01.srvs.cloudkafka.com:9094
  client:
    username: ah1t9hk0
    password: QvMB75cxJ48KYRnGfwXcRNxzALyAeb7-
  group_id: my-group
  topic: ah1t9hk0-default

writer:
  brokers:
    - tricycle-01.srvs.cloudkafka.com:9094
    - tricycle-02.srvs.cloudkafka.com:9094
    - tricycle-03.srvs.cloudkafka.com:9094
  client:
    username: ah1t9hk0
    password: QvMB75cxJ48KYRnGfwXcRNxzALyAeb7-
  topic: ah1t9hk0-default
